### ISSUE TITLE
Build Errors and Fixes for successful compilation

### ISSUE THREAD

**Issue by Pranjali-Innominds** [Audioreach/audioreach-engine#1]
Hello,

I encountered few build errors while compiling the Audio Reach Engine project. After fixing the issues and making the necessary changes, the build process completed successfully. Below are the details of the errors and the corresponding fixes.

Error 1:
Build Error in ar_guids.h Due to Misformatted Comment.
Encountered the following error during the build:

error: expected ';' after top-level declarator in ar_guids.h at line 25

Fix: Change

* GUID owner is Qualcomm.
to

/* GUID owner is Qualcomm. */
This resolves the issue.

Error 2:
Build Error: Too Few Arguments in AR_MSG Macro
Encountered the following error during the build:

error: too few arguments to function call, expected at least 6, have 5

Fix: Updated ar_msg.h at line no 115 to pass the missing argument to ar_log():

- ar_log( xx_ss_mask, msg_tag, filename, line_no, xx_fmt, ##__VA_ARGS__);
+ ar_log( xx_ss_mask, msg_tag, filename, __FUNCTION__, line_no, xx_fmt, ##__VA_ARGS__);
This resolves the issue.

Error 3:
Build Error: Missing Prototype for posal_memorymap_global_unmap_all
Encountered the following error during the build:

error: passing arguments to 'posal_memorymap_global_unmap_all' without a prototype is deprecated in all versions of C and is not supported in C2x

Fix: Updated the function prototype in posal_memorymap.h:

- void posal_memorymap_global_unmap_all();
+ void posal_memorymap_global_unmap_all(int param);
This resolves the issue.

Hope this helps anyone facing similar issues!

**Comment by quic-aditrath** [comment]
Thank you, @Pranjali-Innominds, for identifying the compilation issues on C2X and providing the necessary fixes.
Will incorporate your fixes and raise the changes on mainline.

**Comment by quic-aditrath** [comment]
Thank you, @Pranjali-Innominds, for identifying the compilation issues on C2X and providing the necessary fixes.
Will incorporate your fixes and raise the changes on mainline

**Comment by anonymix007** [comment]
Looks like it still doesn't compile with the Hexagon SDK 6.1.0.1 even with these changes.
I guess the issue is the following lines:
https://github.com/Audioreach/audioreach-engine/blob/master/scripts/cmake/hexagon-toolchain.cmake#L38..L40

Please unhardcode these and also [allow](https://github.com/Audioreach/audioreach-engine/blob/master/scripts/cmake/hexagon-toolchain.cmake#L29) building for newer architectures (i.e. v73)

Will the full source code for posal and platform build be uploaded (`CONFIG_DISABLE_PLATFORM=n` & `CONFIG_COMPILE_POSAL=y`)?

**Comment by quic-aditrath** [comment]
Hi @Pranjali-Innominds, code changes addressing the errors have been merged into the mainline. 

Here are the changes:
- [audioreach-engine: fix comment formatting · Audioreach/audioreach-engine@8f4da2b](https://github.com/Audioreach/audioreach-engine/commit/8f4da2bec835b12725b603ec6c04823754d6026d)
- [CMake: Define preprocessor ARSDK_BUILD_ENABLED for AudioReach SDK build · Audioreach/audioreach-engine@6c1131e](https://github.com/Audioreach/audioreach-engine/commit/6c1131e23b6f824ec6b6440c0ff876a2394b00de)
- [fwk: Remove not needed argument in posal memorymap global unmap API call · Audioreach/audioreach-engine@80d4b12](https://github.com/Audioreach/audioreach-engine/commit/80d4b1261d70646668905487fe9af26fe0f40c23)
